"""Generate a high-level PDF overview of Clawscript."""
from fpdf import FPDF

OUT = "Clawscript-Overview.pdf"


class Doc(FPDF):
    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("Helvetica", "", 8)
        self.set_text_color(120)
        self.cell(0, 6, "Clawscript v0.1 -- Overview", align="L")
        self.cell(0, 6, f"Page {self.page_no()}", align="R")
        self.ln(8)
        self.set_text_color(0)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(150)
        self.cell(0, 6, "Generated by make_pdf.py -- 2026-04-17", align="C")
        self.set_text_color(0)

    def h1(self, text):
        self.set_font("Helvetica", "B", 22)
        self.ln(2)
        self.cell(0, 12, text, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(50)
        self.set_line_width(0.5)
        y = self.get_y()
        self.line(self.l_margin, y, self.w - self.r_margin, y)
        self.ln(4)

    def h2(self, text):
        self.set_font("Helvetica", "B", 14)
        self.ln(3)
        self.cell(0, 8, text, new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def h3(self, text):
        self.set_font("Helvetica", "B", 11)
        self.ln(2)
        self.cell(0, 6, text, new_x="LMARGIN", new_y="NEXT")

    def body(self, text):
        self.set_font("Helvetica", "", 10.5)
        self.multi_cell(0, 5.2, text)
        self.ln(1)

    def mono(self, text):
        self.set_font("Courier", "", 9)
        self.set_fill_color(245, 245, 245)
        self.multi_cell(0, 4.6, text, fill=True, border=0)
        self.set_font("Helvetica", "", 10.5)
        self.ln(1)

    def bullets(self, items):
        self.set_font("Helvetica", "", 10.5)
        for it in items:
            self.set_x(self.l_margin + 4)
            self.multi_cell(0, 5.2, f"*  {it}")
        self.ln(1)

    def table(self, rows, col_widths, header_bold=True):
        self.set_font("Helvetica", "B" if header_bold else "", 9.5)
        self.set_fill_color(230, 230, 235)
        for i, cell in enumerate(rows[0]):
            self.cell(col_widths[i], 7, cell, border=1, fill=True)
        self.ln()
        self.set_font("Helvetica", "", 9)
        for row in rows[1:]:
            heights = [
                self.get_string_width(cell) / (col_widths[i] - 2) * 4 + 4
                for i, cell in enumerate(row)
            ]
            h = max(7, int(max(heights)))
            x0 = self.get_x()
            y0 = self.get_y()
            for i, cell in enumerate(row):
                self.rect(x0, y0, col_widths[i], h)
                self.set_xy(x0 + 1, y0 + 1)
                self.multi_cell(col_widths[i] - 2, 4, cell, border=0)
                x0 += col_widths[i]
                self.set_xy(x0, y0)
            self.set_xy(self.l_margin, y0 + h)
        self.ln(2)


def build():
    pdf = Doc()
    pdf.set_auto_page_break(True, margin=16)
    pdf.set_margins(18, 18, 18)

    # ---- Cover ----
    pdf.add_page()
    pdf.ln(40)
    pdf.set_font("Helvetica", "B", 36)
    pdf.cell(0, 18, "Clawscript", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 14)
    pdf.set_text_color(90)
    pdf.cell(0, 9, "A Python-syntactic language for Claude-executed agents", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 9, "with deterministic flow control.", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0)
    pdf.ln(20)
    pdf.set_font("Helvetica", "", 10.5)
    pdf.cell(0, 6, "Version 0.1  -  Working name: cls  -  2026-04-17", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(60)
    pdf.set_font("Courier", "", 9)
    pdf.set_fill_color(245, 245, 245)
    pdf.multi_cell(0, 4.6,
        "  $ python3 clw.py examples/research.clw --trace run.jsonl\n"
        "  $ tail -2 run.jsonl\n"
        "  {\"step\":17,\"event\":\"checkpoint\",\"label\":\"finalized\",...}\n"
        "  {\"step\":18,\"event\":\"program_end\",\"status\":\"ok\"}",
        fill=True)

    # ---- What is it ----
    pdf.add_page()
    pdf.h1("1. What is Clawscript?")
    pdf.body(
        "Clawscript (cls) is a small programming language for writing "
        "agent programs that a Claude-based runtime executes step-by-step. "
        "Its source syntax is identical to Python 3.11+ at the grammar level: "
        "every valid Clawscript file also parses under Python's ast module. "
        "Its semantics, however, are purpose-built for deterministic agent "
        "execution rather than general-purpose computation."
    )
    pdf.h2("Why it exists")
    pdf.body(
        "Claude Code \"Skills\" are markdown instructions loaded into the model's "
        "context. They are cheap to author but give the model broad latitude: "
        "silent retries, reworded prompts, ad-hoc branching, tool substitution. "
        "That latitude is an asset for exploration and a liability for anything "
        "you would want to audit after the fact. Clawscript trades the "
        "latitude for auditability."
    )
    pdf.h2("The core idea")
    pdf.bullets([
        "Write the agent's control flow as code, not prose.",
        "Parse the code into an AST with Python's own parser.",
        "Walk the AST node-by-node; each statement emits a trace record.",
        "Route LLM sub-calls (prompt) and external effects (tool) through "
        "typed primitives that cannot be skipped, reordered, or paraphrased.",
        "Reject at validation time any program that breaks the rules.",
    ])

    # ---- How it works ----
    pdf.add_page()
    pdf.h1("2. How it works")
    pdf.h2("Pipeline")
    pdf.mono(
        "  source.clw\n"
        "     |\n"
        "     v\n"
        "  [ ast.parse ]  -- Python's own parser; zero custom syntax\n"
        "     |\n"
        "     v\n"
        "  [ Validator ]  -- static rules: no unbounded while, no import,\n"
        "     |              prompt() literal checks, etc.\n"
        "     v\n"
        "  [ Interpreter._exec ]  -- walks Module.body in order;\n"
        "     |                      emits one 'step' trace per statement\n"
        "     v\n"
        "  [ built-ins ]  -- prompt/tool/assert_invariant/checkpoint/\n"
        "     |              require_approval/bounded_loop/typed\n"
        "     v\n"
        "  JSONL trace  +  print() output  +  (optional) LLM responses"
    )
    pdf.h2("Two execution modes")
    pdf.bullets([
        "Python harness (clw.py) -- Python walks the AST; Claude is called "
        "only for prompt() and tool() steps via the Anthropic SDK.",
        "Claude-as-interpreter -- load RUNTIME.md as the system prompt; "
        "hand Claude the source plus AST; Claude itself walks the tree "
        "under the ten explicit prohibitions.",
    ])

    # ---- Rules ----
    pdf.add_page()
    pdf.h1("3. The six flow-control rules")
    pdf.body(
        "Every Clawscript interpreter must enforce these at runtime. "
        "They are the entire reason the language exists."
    )
    rules = [
        ("No implicit retries", "A tool() or prompt() failure raises. "
         "Control flows only to a matching except. The runtime never "
         "reissues the call on its own."),
        ("No unbounded loops", "A while loop must be inside a function "
         "decorated @bounded_loop(N) where N is an integer literal. "
         "Iteration N+1 auto-raises BoundExceeded."),
        ("No hidden state", "All step-to-step data must pass through an "
         "explicitly bound name visible in source."),
        ("No paraphrase of prompts", "prompt(model, text) sends text "
         "byte-for-byte. The validator forces text to be a string literal "
         "or f-string so it is readable in source."),
        ("No skipping invariants", "assert_invariant halts on falsy. "
         "There is no optimization mode that elides it."),
        ("Checkpoints are verbatim", "Every checkpoint(label, **data) "
         "emits one JSONL record whose label matches the source-level "
         "string literal exactly."),
    ]
    for i, (name, desc) in enumerate(rules, 1):
        pdf.h3(f"{i}. {name}")
        pdf.body(desc)

    # ---- Built-ins ----
    pdf.add_page()
    pdf.h1("4. Built-in primitives")
    builtins = [
        ("prompt(model, text) -> str",
         "Single LLM sub-call. model must be a string literal; text must "
         "be a literal or f-string. Sent byte-for-byte."),
        ("tool(name, **kwargs) -> Any",
         "Exact-name dispatch into the tool registry. Unknown name raises "
         "KeyError -- no nearest-match substitution."),
        ("assert_invariant(expr, msg)",
         "Halts the program if expr is falsy. Not elidable."),
        ("checkpoint(label, **data)",
         "Emits a structured JSONL trace event. label must be a string "
         "literal."),
        ("require_approval(action)",
         "Pauses for a human operator; denial raises ApprovalDenied."),
        ("@bounded_loop(N)",
         "Function decorator. Any while inside is capped at N iterations. "
         "N must be an integer literal."),
        ("@typed",
         "Function decorator. On each call, every annotated parameter is "
         "isinstance-checked against its hint; return value likewise."),
    ]
    for name, desc in builtins:
        pdf.h3(name)
        pdf.body(desc)

    # ---- Architecture ----
    pdf.add_page()
    pdf.h1("5. Reference interpreter (clw.py)")
    pdf.body(
        "About 480 lines of Python. Structure:"
    )
    pdf.bullets([
        "Env -- lexical scope chain with get/set/flatten.",
        "Tracer -- JSONL sink with monotonic step counter.",
        "Validator(ast.NodeVisitor) -- runs before any execution; rejects "
        "programs that break the static rules.",
        "Built-in factories -- make_prompt, make_tool, make_assert_invariant, "
        "make_checkpoint, make_require_approval, make_bounded_loop, make_typed. "
        "Each closes over the tracer so every external effect is logged.",
        "Interpreter -- the AST walker. One _stmt_X handler per supported "
        "statement type (Assign, If, For, While, Try, Return, FunctionDef, "
        "ClassDef, Raise, Assert, AugAssign, AnnAssign, Break, Continue, Pass, Expr).",
        "Expression evaluation is delegated to Python's eval() with a safe "
        "builtins allow-list; expressions cannot re-enter control flow, so "
        "this is safe and avoids several hundred lines of boilerplate.",
    ])
    pdf.h2("Key design choices")
    pdf.bullets([
        "Built-ins injected into Env, not pattern-matched in the walker -- "
        "so nested expressions still intercept.",
        "@bounded_loop enforced via a push/pop stack on the interpreter; "
        "_stmt_While reads the top on each iteration. Supports nesting.",
        "ast.parse filename preserved for line-accurate trace records.",
        "SAFE_BUILTINS is an allow-list, not a deny-list -- new Python "
        "builtins default to inaccessible.",
        "Validator runs before program_start is emitted -- an invalid "
        "program produces zero execution trace records.",
    ])

    # ---- Examples ----
    pdf.add_page()
    pdf.h1("6. Example programs")
    pdf.h2("research.clw -- linear research pipeline")
    pdf.body(
        "fetch -> summarize -> critique -> finalize. Four checkpoint records, "
        "two invariants, three prompt() calls each pinned to a specific model."
    )
    pdf.h2("retry_backoff.clw -- bounded retry")
    pdf.body(
        "A while loop decorated @bounded_loop(5). After five failures the "
        "cap engages automatically. The programmer cannot forget the cap "
        "and the interpreter cannot 'try one more time' on its own."
    )
    pdf.h2("approval.clw -- human-in-the-loop")
    pdf.body(
        "Prepares a plan with an LLM, prints it, hard-gates the irreversible "
        "step behind require_approval(). Denial raises ApprovalDenied -- no "
        "fallback path, no retry, no prompt rewording."
    )

    # ---- Comparison ----
    pdf.add_page()
    pdf.h1("7. vs. Skills vs. raw prompting")
    rows = [
        ["Dimension", "Clawscript", "Skills", "Raw prompting"],
        ["Step order determinism", "Total - AST walk enforced", "Low - model picks", "None"],
        ["Tool dispatch", "Exact-name; KeyError on miss", "Description-match; may substitute", "N/A"],
        ["Trace schema", "Stable JSONL, per-event fields", "Transcript + tool blocks", "Transcript"],
        ["Retries on failure", "Never implicit; except only", "Implicit; silent reword-retry", "None"],
        ["Loop safety", "@bounded_loop(N) literal cap", "No loop primitive", "None"],
        ["Prompt fidelity", "Byte-for-byte; source-visible", "May paraphrase", "Model composes"],
        ["Invariants", "Halt on violation", "Soft markdown 'should'", "None"],
        ["Human approval", "First-class primitive", "Per-skill, ad hoc", "Out-of-band"],
        ["Flexibility", "Low by design", "High", "Highest"],
        ["Authoring cost", "Higher - write code", "Low - write markdown", "Lowest"],
        ["Latency", "Higher", "Variable", "Lowest"],
        ["Best for", "Compliance, runbooks, deploys", "Exploratory tools", "One-shot drafts"],
    ]
    pdf.table(rows, col_widths=[44, 46, 42, 42])

    pdf.h2("One-paragraph summary")
    pdf.body(
        "Clawscript and Skills sit at opposite ends of a determinism-"
        "flexibility axis. Skills give the model broad latitude inside a "
        "markdown scaffold -- cheap to author, easy to use, hard to audit. "
        "Clawscript gives the model none: every decision is an AST node, "
        "every external effect is a trace record, every loop has an integer "
        "cap in source. Pick Skills for exploration, Clawscript for "
        "anything you would want to read a post-incident trace of."
    )

    pdf.output(OUT)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    build()
